//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleQ.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über SimpleQ ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersicht ähnelt.
        /// </summary>
        internal static string Abstract {
            get {
                return ResourceManager.GetString("Abstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Kategorien ähnelt.
        /// </summary>
        internal static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Antwort ähnelt.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /answerSurvey ähnelt.
        /// </summary>
        internal static string APIAnswerSurveyPlusURL {
            get {
                return ResourceManager.GetString("APIAnswerSurveyPlusURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /getSurveyData ähnelt.
        /// </summary>
        internal static string APIGetDataPlusURL {
            get {
                return ResourceManager.GetString("APIGetDataPlusURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /joinDepartment ähnelt.
        /// </summary>
        internal static string APIJoinDepartmentPlusURL {
            get {
                return ResourceManager.GetString("APIJoinDepartmentPlusURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /leaveDepartment ähnelt.
        /// </summary>
        internal static string APILeaveDepartmentPlusURL {
            get {
                return ResourceManager.GetString("APILeaveDepartmentPlusURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://simpleq.at/api/mobile ähnelt.
        /// </summary>
        internal static string APIMainURL {
            get {
                return ResourceManager.GetString("APIMainURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /register ähnelt.
        /// </summary>
        internal static string APIRegisterPlusURL {
            get {
                return ResourceManager.GetString("APIRegisterPlusURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /unregister ähnelt.
        /// </summary>
        internal static string APIUnregisterPlusURL {
            get {
                return ResourceManager.GetString("APIUnregisterPlusURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App Informationen ähnelt.
        /// </summary>
        internal static string AppInformation {
            get {
                return ResourceManager.GetString("AppInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ändern ähnelt.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code wird überprüft ähnelt.
        /// </summary>
        internal static string CheckCode {
            get {
                return ResourceManager.GetString("CheckCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll sich die App, nach dem Beantworten einer neuen Frage, wieder schließen? ähnelt.
        /// </summary>
        internal static string CloseAppAfterNotification {
            get {
                return ResourceManager.GetString("CloseAppAfterNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontakt ähnelt.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kontaktieren Sie unseren Support ähnelt.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright © 2018 by SimpleQ ähnelt.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehlercode ähnelt.
        /// </summary>
        internal static string DialogErrorCode {
            get {
                return ResourceManager.GetString("DialogErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string DialogErrorTitle {
            get {
                return ResourceManager.GetString("DialogErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiß nicht ähnelt.
        /// </summary>
        internal static string DontKnow {
            get {
                return ResourceManager.GetString("DontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die admin@juerweb.com ähnelt.
        /// </summary>
        internal static string EmailAdress {
            get {
                return ResourceManager.GetString("EmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schreiben Sie uns eine E-Mail ähnelt.
        /// </summary>
        internal static string EmailUs {
            get {
                return ResourceManager.GetString("EmailUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der QR-Code entspricht nicht dem richtigen Format. Verwenden Sie bitte einen anderen QR-Code. ähnelt.
        /// </summary>
        internal static string Error101 {
            get {
                return ResourceManager.GetString("Error101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der eingegebene Registrierungscode ist nicht im System registriert. Verwenden Sie bitte einen anderen Registrierungscode. ähnelt.
        /// </summary>
        internal static string Error201 {
            get {
                return ResourceManager.GetString("Error201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterte Hilfe ähnelt.
        /// </summary>
        internal static string ExtendedHelp {
            get {
                return ResourceManager.GetString("ExtendedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterte Hilfe (Internet) ähnelt.
        /// </summary>
        internal static string ExtendedHelpInternet {
            get {
                return ResourceManager.GetString("ExtendedHelpInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FAQ ähnelt.
        /// </summary>
        internal static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeine Einstellungen ähnelt.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SimpleQ.Resources.private.key ähnelt.
        /// </summary>
        internal static string KeyResourcename {
            get {
                return ResourceManager.GetString("KeyResourcename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.google.at ähnelt.
        /// </summary>
        internal static string LinkToContactForm {
            get {
                return ResourceManager.GetString("LinkToContactForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://support.google.com/ ähnelt.
        /// </summary>
        internal static string LinkToSupportWebsite {
            get {
                return ResourceManager.GetString("LinkToSupportWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.google.at/ ähnelt.
        /// </summary>
        internal static string LinkToWebsite {
            get {
                return ResourceManager.GetString("LinkToWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SimpleQ.Resources.Images.logo.png ähnelt.
        /// </summary>
        internal static string LogoResourcename {
            get {
                return ResourceManager.GetString("LogoResourcename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abmelden ähnelt.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Ste [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alternative: Geben Sie den Code manuell ein ähnelt.
        /// </summary>
        internal static string ManuelCodeEntry {
            get {
                return ResourceManager.GetString("ManuelCodeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menü ähnelt.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SimpleQ ähnelt.
        /// </summary>
        internal static string NameOfApp {
            get {
                return ResourceManager.GetString("NameOfApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Elemente in dieser Kategorie ähnelt.
        /// </summary>
        internal static string NothingIn {
            get {
                return ResourceManager.GetString("NothingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die +43 00000000000 ähnelt.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rufen Sie uns an ähnelt.
        /// </summary>
        internal static string PhoneUs {
            get {
                return ResourceManager.GetString("PhoneUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sind Sie sich wirklich sicher? ähnelt.
        /// </summary>
        internal static string ReallySure {
            get {
                return ResourceManager.GetString("ReallySure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten abrufen ähnelt.
        /// </summary>
        internal static string RecallData {
            get {
                return ResourceManager.GetString("RecallData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registrierungscode ähnelt.
        /// </summary>
        internal static string RegisterCode {
            get {
                return ResourceManager.GetString("RegisterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scannen Sie den QR-Code, welchen Sie von Ihrem Unternehmen erhalten haben. ähnelt.
        /// </summary>
        internal static string RegisterScanHelpText {
            get {
                return ResourceManager.GetString("RegisterScanHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wählen sie eine neue Sprache aus. ähnelt.
        /// </summary>
        internal static string SelectALanguage {
            get {
                return ResourceManager.GetString("SelectALanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Antwort senden ähnelt.
        /// </summary>
        internal static string SendAnswer {
            get {
                return ResourceManager.GetString("SendAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scan starten 📷 ähnelt.
        /// </summary>
        internal static string StartScan {
            get {
                return ResourceManager.GetString("StartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 ähnelt.
        /// </summary>
        internal static string UpdateInterval {
            get {
                return ResourceManager.GetString("UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Besuchen Sie unsere Website ähnelt.
        /// </summary>
        internal static string VisitUs {
            get {
                return ResourceManager.GetString("VisitUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
