//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BackendResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackendResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleQ.Webinterface.Properties.BackendResources", typeof(BackendResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting period must either 1, 3, 6 or 12 months..
        /// </summary>
        internal static string AccountingPeriodInvalid {
            get {
                return ResourceManager.GetString("AccountingPeriodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be at least 1..
        /// </summary>
        internal static string AmountMustAtLeast1 {
            get {
                return ResourceManager.GetString("AmountMustAtLeast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer options must not be empty..
        /// </summary>
        internal static string AnswerOptionsNotEmpty {
            get {
                return ResourceManager.GetString("AnswerOptionsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one answer type does not exist..
        /// </summary>
        internal static string AnswerTypeDoesNotExist {
            get {
                return ResourceManager.GetString("AnswerTypeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer type does not exist..
        /// </summary>
        internal static string AnswerTypeNotExist {
            get {
                return ResourceManager.GetString("AnswerTypeNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be selected at least one answer type..
        /// </summary>
        internal static string AnswerTypesNull {
            get {
                return ResourceManager.GetString("AnswerTypesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-generated bill document.
        /// </summary>
        internal static string AutoGeneratedBillDoc {
            get {
                return ResourceManager.GetString("AutoGeneratedBillDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary.
        /// </summary>
        internal static string Beneficiary {
            get {
                return ResourceManager.GetString("Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best regards,.
        /// </summary>
        internal static string BestRegards {
            get {
                return ResourceManager.GetString("BestRegards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        internal static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Sir or Madam!&lt;br/&gt;
        ///&lt;br/&gt;
        ///Enclosed you will find your most recent bill.&lt;br/&gt;
        ///For further questions please contact support@simpleq.at.&lt;br/&gt;
        ///&lt;br/&gt;
        ///Sincerely,&lt;br/&gt;
        ///Your SimpleQ team&lt;br/&gt;.
        /// </summary>
        internal static string BillEmailMessage {
            get {
                return ResourceManager.GetString("BillEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleQ Bill.
        /// </summary>
        internal static string BillEmailSubject {
            get {
                return ResourceManager.GetString("BillEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill number.
        /// </summary>
        internal static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found..
        /// </summary>
        internal static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must not be empty..
        /// </summary>
        internal static string CityEmpty {
            get {
                return ResourceManager.GetString("CityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed due to internal error(s)..
        /// </summary>
        internal static string ConfirmationSendingFailedMsg {
            get {
                return ResourceManager.GetString("ConfirmationSendingFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send confirmation e-mail.
        /// </summary>
        internal static string ConfirmationSendingFailedTitle {
            get {
                return ResourceManager.GetString("ConfirmationSendingFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email before creating surveys..
        /// </summary>
        internal static string ConfirmYourEmailMsg {
            get {
                return ResourceManager.GetString("ConfirmYourEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email.
        /// </summary>
        internal static string ConfirmYourEmailTitle {
            get {
                return ResourceManager.GetString("ConfirmYourEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country must not be empty..
        /// </summary>
        internal static string CountryEmpty {
            get {
                return ResourceManager.GetString("CountryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid customer code or password..
        /// </summary>
        internal static string CustCodeOrPwdInvalid {
            get {
                return ResourceManager.GetString("CustCodeOrPwdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code.
        /// </summary>
        internal static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current customer was not found..
        /// </summary>
        internal static string CustomerNotFoundMsg {
            get {
                return ResourceManager.GetString("CustomerNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        internal static string CustomerNotFoundTitle {
            get {
                return ResourceManager.GetString("CustomerNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data storage period must be at least 1 month..
        /// </summary>
        internal static string DataStoragePeriodInvalid {
            get {
                return ResourceManager.GetString("DataStoragePeriodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid day value..
        /// </summary>
        internal static string DayInvalid {
            get {
                return ResourceManager.GetString("DayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        internal static string DefaultErrorMsg {
            get {
                return ResourceManager.GetString("DefaultErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group not found..
        /// </summary>
        internal static string DepNotFound {
            get {
                return ResourceManager.GetString("DepNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be specified at least one email address..
        /// </summary>
        internal static string EmailAdressesEmpty {
            get {
                return ResourceManager.GetString("EmailAdressesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does already exist..
        /// </summary>
        internal static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must not be empty..
        /// </summary>
        internal static string EmailEmpty {
            get {
                return ResourceManager.GetString("EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed due to internal error(s)..
        /// </summary>
        internal static string EmailSendingFailedMessage {
            get {
                return ResourceManager.GetString("EmailSendingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send email.
        /// </summary>
        internal static string EmailSendingFailedTitle {
            get {
                return ResourceManager.GetString("EmailSendingFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee satisfaction.
        /// </summary>
        internal static string EmployeeSatisfaction {
            get {
                return ResourceManager.GetString("EmployeeSatisfaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone.
        /// </summary>
        internal static string Everyone {
            get {
                return ResourceManager.GetString("Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password reset link is not valid anymore..
        /// </summary>
        internal static string ExpiredPasswordResetMsg {
            get {
                return ResourceManager.GetString("ExpiredPasswordResetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired reset link.
        /// </summary>
        internal static string ExpiredPasswordResetTitle {
            get {
                return ResourceManager.GetString("ExpiredPasswordResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading survey failed.
        /// </summary>
        internal static string FailedLoadingSurvey {
            get {
                return ResourceManager.GetString("FailedLoadingSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Sir or Madam!&lt;br/&gt;
        ///&lt;br/&gt;
        ///To reset your email click the following link: {Url}&lt;br/&gt;
        ///The link is valid for 15 minutes.&lt;br/&gt;
        ///&lt;br/&gt;
        ///Sincerely,&lt;br/&gt;
        ///Your SimpleQ team&lt;br/&gt;.
        /// </summary>
        internal static string ForgotPasswordEmailMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleQ password reset.
        /// </summary>
        internal static string ForgotPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear customer,&lt;br/&gt;
        ///you got invited to participate in surveys provided by SimpleQ!&lt;br/&gt;
        ///&lt;br/&gt;
        ///Please scan the attached QR code with your SimpleQ app.&lt;br/&gt;
        ///Alternatively you can enter the following registration code in your app: {RegCode}&lt;br/&gt;
        ///Sincerely,&lt;br/&gt;
        ///Your SimpleQ team&lt;br/&gt;.
        /// </summary>
        internal static string GroupInvitationEmailMessage {
            get {
                return ResourceManager.GetString("GroupInvitationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration code: {RegCode}
        ///Message:
        ///{CustomMessage}.
        /// </summary>
        internal static string GroupInvitationEmailMessageCustom {
            get {
                return ResourceManager.GetString("GroupInvitationEmailMessageCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleQ invitation.
        /// </summary>
        internal static string GroupInvitationEmailSubject {
            get {
                return ResourceManager.GetString("GroupInvitationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed due to internal error(s)..
        /// </summary>
        internal static string GroupInvitationSendingFailedMsg {
            get {
                return ResourceManager.GetString("GroupInvitationSendingFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send invitation e-mails.
        /// </summary>
        internal static string GroupInvitationSendingFailedTitle {
            get {
                return ResourceManager.GetString("GroupInvitationSendingFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email confirmation link is not valid..
        /// </summary>
        internal static string InvalidConfirmationLinkMsg {
            get {
                return ResourceManager.GetString("InvalidConfirmationLinkMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid confirmation link.
        /// </summary>
        internal static string InvalidConfirmationLinkTitle {
            get {
                return ResourceManager.GetString("InvalidConfirmationLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password reset link is not valid..
        /// </summary>
        internal static string InvalidPasswordResetMsg {
            get {
                return ResourceManager.GetString("InvalidPasswordResetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid reset link.
        /// </summary>
        internal static string InvalidPasswordResetTitle {
            get {
                return ResourceManager.GetString("InvalidPasswordResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language must not be empty..
        /// </summary>
        internal static string LangCodeEmpty {
            get {
                return ResourceManager.GetString("LangCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint: Exempted from value-added tax – small entrepreneur pursuant to § 6 Abs. 1 Z 27 UStG.
        /// </summary>
        internal static string LegalHint {
            get {
                return ResourceManager.GetString("LegalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be submitted data..
        /// </summary>
        internal static string ModelNull {
            get {
                return ResourceManager.GetString("ModelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must not be empty..
        /// </summary>
        internal static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not created any surveys yet..
        /// </summary>
        internal static string NoSurveysMsg {
            get {
                return ResourceManager.GetString("NoSurveysMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No surveys.
        /// </summary>
        internal static string NoSurveysTitle {
            get {
                return ResourceManager.GetString("NoSurveysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of answers.
        /// </summary>
        internal static string NumOfAnswers {
            get {
                return ResourceManager.GetString("NumOfAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method does not exist..
        /// </summary>
        internal static string PaymentMethodInvalid {
            get {
                return ResourceManager.GetString("PaymentMethodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period must be at least 1 day..
        /// </summary>
        internal static string PeriodAtLeast1Day {
            get {
                return ResourceManager.GetString("PeriodAtLeast1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period must be bigger than the survey&apos;s duration..
        /// </summary>
        internal static string PeriodMustBiggerThanDuration {
            get {
                return ResourceManager.GetString("PeriodMustBiggerThanDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code must not be empty..
        /// </summary>
        internal static string PlzEmpty {
            get {
                return ResourceManager.GetString("PlzEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to present.
        /// </summary>
        internal static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per click.
        /// </summary>
        internal static string PricePerClick {
            get {
                return ResourceManager.GetString("PricePerClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered passwords do not match..
        /// </summary>
        internal static string PwdDontMatch {
            get {
                return ResourceManager.GetString("PwdDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        internal static string PwdTooShort {
            get {
                return ResourceManager.GetString("PwdTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a question category..
        /// </summary>
        internal static string QuestionCategoryEmpty {
            get {
                return ResourceManager.GetString("QuestionCategoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question text must not be empty..
        /// </summary>
        internal static string QuestionTextEmpty {
            get {
                return ResourceManager.GetString("QuestionTextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to SimpleQ!&lt;br/&gt;
        ///&lt;br/&gt;
        ///Please confirm your e-mail address now.&lt;br/&gt;
        ///Hence just click the following confirmation link: {Url}&lt;br/&gt;
        ///Your customer code: {CustCode}&lt;br/&gt;
        ///&lt;br/&gt;
        ///Sincerely,&lt;br/&gt;
        ///Your SimpleQ team&lt;br/&gt;.
        /// </summary>
        internal static string RegistrationEmailMessage {
            get {
                return ResourceManager.GetString("RegistrationEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleQ email confirmation.
        /// </summary>
        internal static string RegistrationEmailSubject {
            get {
                return ResourceManager.GetString("RegistrationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be selected at least one group.
        /// </summary>
        internal static string SelectedDepartmentsEmpty {
            get {
                return ResourceManager.GetString("SelectedDepartmentsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service period.
        /// </summary>
        internal static string ServicePeriod {
            get {
                return ResourceManager.GetString("ServicePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleQ Bill.
        /// </summary>
        internal static string SimpleQBill {
            get {
                return ResourceManager.GetString("SimpleQBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be earlier than end date..
        /// </summary>
        internal static string StartDateMustEarlierEndDate {
            get {
                return ResourceManager.GetString("StartDateMustEarlierEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street must not be empty..
        /// </summary>
        internal static string StreetEmpty {
            get {
                return ResourceManager.GetString("StreetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be specified exactly two answer options..
        /// </summary>
        internal static string Submit2AnswerOptions {
            get {
                return ResourceManager.GetString("Submit2AnswerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be specified at least one answer option..
        /// </summary>
        internal static string SubmitAnswerOptions {
            get {
                return ResourceManager.GetString("SubmitAnswerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        internal static string Survey {
            get {
                return ResourceManager.GetString("Survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey not found..
        /// </summary>
        internal static string SurveyNotFound {
            get {
                return ResourceManager.GetString("SurveyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be submitted survey data..
        /// </summary>
        internal static string SurveyNull {
            get {
                return ResourceManager.GetString("SurveyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey price.
        /// </summary>
        internal static string SurveyPrice {
            get {
                return ResourceManager.GetString("SurveyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey text must not be empty..
        /// </summary>
        internal static string SurveyTextEmpty {
            get {
                return ResourceManager.GetString("SurveyTextEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cost.
        /// </summary>
        internal static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workplace design.
        /// </summary>
        internal static string WorkplaceDesign {
            get {
                return ResourceManager.GetString("WorkplaceDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your SimpleQ team.
        /// </summary>
        internal static string YourSimpleQTeam {
            get {
                return ResourceManager.GetString("YourSimpleQTeam", resourceCulture);
            }
        }
    }
}
