//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleQ.Webinterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add answer.
        /// </summary>
        public static string addAnswer {
            get {
                return ResourceManager.GetString("addAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add mail address.
        /// </summary>
        public static string addMailAddress {
            get {
                return ResourceManager.GetString("addMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string addNewCategory {
            get {
                return ResourceManager.GetString("addNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address data.
        /// </summary>
        public static string addressData {
            get {
                return ResourceManager.GetString("addressData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        public static string answers {
            get {
                return ResourceManager.GetString("answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add answers.
        /// </summary>
        public static string answersButtonTooltip {
            get {
                return ResourceManager.GetString("answersButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer type.
        /// </summary>
        public static string answerTypeHeader {
            get {
                return ResourceManager.GetString("answerTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of asked people.
        /// </summary>
        public static string askedPeopleCount {
            get {
                return ResourceManager.GetString("askedPeopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small group, to get good results create a bigger one.
        /// </summary>
        public static string badAskGroupCount {
            get {
                return ResourceManager.GetString("badAskGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string bar {
            get {
                return ResourceManager.GetString("bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base data.
        /// </summary>
        public static string baseData {
            get {
                return ResourceManager.GetString("baseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing period in months.
        /// </summary>
        public static string billingPeriodInMonths {
            get {
                return ResourceManager.GetString("billingPeriodInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an category with this name .
        /// </summary>
        public static string categoryAlreadyExists {
            get {
                return ResourceManager.GetString("categoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the customer code you got in your validation mail.
        /// </summary>
        public static string custCodeTooltip {
            get {
                return ResourceManager.GetString("custCodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer code.
        /// </summary>
        public static string customerCode {
            get {
                return ResourceManager.GetString("customerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        public static string customerName {
            get {
                return ResourceManager.GetString("customerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data storage period in months.
        /// </summary>
        public static string dataRetentionPeriodInMonths {
            get {
                return ResourceManager.GetString("dataRetentionPeriodInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not created any groups yet, switch to group administration and create your first one.
        /// </summary>
        public static string defineGroupsModalInfo {
            get {
                return ResourceManager.GetString("defineGroupsModalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        public static string diagram {
            get {
                return ResourceManager.GetString("diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dichotomous.
        /// </summary>
        public static string Dichotomous {
            get {
                return ResourceManager.GetString("Dichotomous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doughnut.
        /// </summary>
        public static string doughnut {
            get {
                return ResourceManager.GetString("doughnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download the app here.
        /// </summary>
        public static string downloadAppHere {
            get {
                return ResourceManager.GetString("downloadAppHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address confirmed.
        /// </summary>
        public static string emailConfirmed {
            get {
                return ResourceManager.GetString("emailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate.
        /// </summary>
        public static string evaluate {
            get {
                return ResourceManager.GetString("evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot passwort.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appropriate size for meaningful results.
        /// </summary>
        public static string goodAskGroupCount {
            get {
                return ResourceManager.GetString("goodAskGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to registration.
        /// </summary>
        public static string goToRegistration {
            get {
                return ResourceManager.GetString("goToRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppenverwaltung.
        /// </summary>
        public static string groupAdministrationHeader {
            get {
                return ResourceManager.GetString("groupAdministrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a group with this name.
        /// </summary>
        public static string groupAlreadyExists {
            get {
                return ResourceManager.GetString("groupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group code.
        /// </summary>
        public static string groupCode {
            get {
                return ResourceManager.GetString("groupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string invalidInput {
            get {
                return ResourceManager.GetString("invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered email address in invalid.
        /// </summary>
        public static string invalidMailAddress {
            get {
                return ResourceManager.GetString("invalidMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation to SimpleQ.
        /// </summary>
        public static string invitationToSimpleQ {
            get {
                return ResourceManager.GetString("invitationToSimpleQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale (3 items).
        /// </summary>
        public static string LikertSkale3 {
            get {
                return ResourceManager.GetString("LikertSkale3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale (4 items).
        /// </summary>
        public static string LikertSkale4 {
            get {
                return ResourceManager.GetString("LikertSkale4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale (5 items).
        /// </summary>
        public static string LikertSkale5 {
            get {
                return ResourceManager.GetString("LikertSkale5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale (6 items).
        /// </summary>
        public static string LikertSkale6 {
            get {
                return ResourceManager.GetString("LikertSkale6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale (7 items).
        /// </summary>
        public static string LikertSkale7 {
            get {
                return ResourceManager.GetString("LikertSkale7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale (8 items).
        /// </summary>
        public static string LikertSkale8 {
            get {
                return ResourceManager.GetString("LikertSkale8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale (9 items).
        /// </summary>
        public static string LikertSkale9 {
            get {
                return ResourceManager.GetString("LikertSkale9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing (absolute, %).
        /// </summary>
        public static string listing {
            get {
                return ResourceManager.GetString("listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group size is OK, although increasing would be beneficial for more meaningful results.
        /// </summary>
        public static string middleAskGroupCount {
            get {
                return ResourceManager.GetString("middleAskGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category name.
        /// </summary>
        public static string newCategoryName {
            get {
                return ResourceManager.GetString("newCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template.
        /// </summary>
        public static string noTemplate {
            get {
                return ResourceManager.GetString("noTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open text answer.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string paymentMethod {
            get {
                return ResourceManager.GetString("paymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to repeat a question certain times automatically.
        /// </summary>
        public static string periodicQuestionTooltip {
            get {
                return ResourceManager.GetString("periodicQuestionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define groups first.
        /// </summary>
        public static string pleaseDefineGroupsFirst {
            get {
                return ResourceManager.GetString("pleaseDefineGroupsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polar area.
        /// </summary>
        public static string polarArea {
            get {
                return ResourceManager.GetString("polarArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many answers, many to choose (ordered).
        /// </summary>
        public static string PolytomousOrderedMultiple {
            get {
                return ResourceManager.GetString("PolytomousOrderedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many answers, one to choose (ordered).
        /// </summary>
        public static string PolytomousOrderedSingle {
            get {
                return ResourceManager.GetString("PolytomousOrderedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many answers, many to choose (unordered).
        /// </summary>
        public static string PolytomousUnorderedMultiple {
            get {
                return ResourceManager.GetString("PolytomousUnorderedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many answers, one to choose (unordered).
        /// </summary>
        public static string PolytomousUnorderedSingle {
            get {
                return ResourceManager.GetString("PolytomousUnorderedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP code.
        /// </summary>
        public static string postCode {
            get {
                return ResourceManager.GetString("postCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted price.
        /// </summary>
        public static string predictedPrice {
            get {
                return ResourceManager.GetString("predictedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred billing date for each month.
        /// </summary>
        public static string preferredBillingDay {
            get {
                return ResourceManager.GetString("preferredBillingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string questionHeader {
            get {
                return ResourceManager.GetString("questionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string questionTimeDateHeader {
            get {
                return ResourceManager.GetString("questionTimeDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string questionTimeTimeHeader {
            get {
                return ResourceManager.GetString("questionTimeTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radar.
        /// </summary>
        public static string radar {
            get {
                return ResourceManager.GetString("radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as template.
        /// </summary>
        public static string SaveAsTemplate {
            get {
                return ResourceManager.GetString("SaveAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send reset link.
        /// </summary>
        public static string sendResetLink {
            get {
                return ResourceManager.GetString("sendResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to get the results of each survey seperately.
        /// </summary>
        public static string singleButtonTooltip {
            get {
                return ResourceManager.GetString("singleButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single evaluation.
        /// </summary>
        public static string singleEvaluation {
            get {
                return ResourceManager.GetString("singleEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single or trend evaluation?.
        /// </summary>
        public static string singleOrTrendEvaluation {
            get {
                return ResourceManager.GetString("singleOrTrendEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single survey evaluation.
        /// </summary>
        public static string singleQuestionEvaluation {
            get {
                return ResourceManager.GetString("singleQuestionEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific data.
        /// </summary>
        public static string specificData {
            get {
                return ResourceManager.GetString("specificData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send survey.
        /// </summary>
        public static string startSurvey {
            get {
                return ResourceManager.GetString("startSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay logged in.
        /// </summary>
        public static string stayLoggedIn {
            get {
                return ResourceManager.GetString("stayLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street and house number.
        /// </summary>
        public static string streetAndHousenumber {
            get {
                return ResourceManager.GetString("streetAndHousenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        public static string strong {
            get {
                return ResourceManager.GetString("strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        public static string survey {
            get {
                return ResourceManager.GetString("survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey category.
        /// </summary>
        public static string surveyCategoryHeader {
            get {
                return ResourceManager.GetString("surveyCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Survey.
        /// </summary>
        public static string surveyCreationHeader {
            get {
                return ResourceManager.GetString("surveyCreationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string surveyPreviewHeader {
            get {
                return ResourceManager.GetString("surveyPreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Results.
        /// </summary>
        public static string surveyResultsHeader {
            get {
                return ResourceManager.GetString("surveyResultsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose template (recent surveys).
        /// </summary>
        public static string surveyTemplateHeader {
            get {
                return ResourceManager.GetString("surveyTemplateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if you intend to repeat the survey later.
        /// </summary>
        public static string TemplateDescription {
            get {
                return ResourceManager.GetString("TemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string textEditorLanguage {
            get {
                return ResourceManager.GetString("textEditorLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timespan.
        /// </summary>
        public static string timespan {
            get {
                return ResourceManager.GetString("timespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To group-administration.
        /// </summary>
        public static string toGroupAdministration {
            get {
                return ResourceManager.GetString("toGroupAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic lights (red, yellow, green).
        /// </summary>
        public static string TrafficLight {
            get {
                return ResourceManager.GetString("TrafficLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to get a trend view of all survey results.
        /// </summary>
        public static string trendButtonTooltip {
            get {
                return ResourceManager.GetString("trendButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend evaluation.
        /// </summary>
        public static string trendEvaluation {
            get {
                return ResourceManager.GetString("trendEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  type.
        /// </summary>
        public static string typeSmall {
            get {
                return ResourceManager.GetString("typeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        public static string weak {
            get {
                return ResourceManager.GetString("weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        public static string weeks {
            get {
                return ResourceManager.GetString("weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No.
        /// </summary>
        public static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No/Don&apos;t know.
        /// </summary>
        public static string YesNoDontKnow {
            get {
                return ResourceManager.GetString("YesNoDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can log in now.
        /// </summary>
        public static string youCanNowLogin {
            get {
                return ResourceManager.GetString("youCanNowLogin", resourceCulture);
            }
        }
    }
}
