//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleQ.Webinterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add answer ähnelt.
        /// </summary>
        public static string addAnswer {
            get {
                return ResourceManager.GetString("addAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add email address ähnelt.
        /// </summary>
        public static string addMailAddress {
            get {
                return ResourceManager.GetString("addMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new category ähnelt.
        /// </summary>
        public static string addNewCategory {
            get {
                return ResourceManager.GetString("addNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address data ähnelt.
        /// </summary>
        public static string addressData {
            get {
                return ResourceManager.GetString("addressData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already started ähnelt.
        /// </summary>
        public static string AlreadyStarted {
            get {
                return ResourceManager.GetString("AlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Answer ähnelt.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The answer already exists ähnelt.
        /// </summary>
        public static string AnswerAlreadyExists {
            get {
                return ResourceManager.GetString("AnswerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Answers ähnelt.
        /// </summary>
        public static string answers {
            get {
                return ResourceManager.GetString("answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click here to add answers ähnelt.
        /// </summary>
        public static string answersButtonTooltip {
            get {
                return ResourceManager.GetString("answersButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Answer type ähnelt.
        /// </summary>
        public static string answerTypeHeader {
            get {
                return ResourceManager.GetString("answerTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount of asked people ähnelt.
        /// </summary>
        public static string askedPeopleCount {
            get {
                return ResourceManager.GetString("askedPeopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die For meaningful results a bigger group would be necessary ähnelt.
        /// </summary>
        public static string badAskGroupCount {
            get {
                return ResourceManager.GetString("badAskGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bar ähnelt.
        /// </summary>
        public static string bar {
            get {
                return ResourceManager.GetString("bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base data ähnelt.
        /// </summary>
        public static string baseData {
            get {
                return ResourceManager.GetString("baseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Billing period in months ähnelt.
        /// </summary>
        public static string billingPeriodInMonths {
            get {
                return ResourceManager.GetString("billingPeriodInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The time between receiving bills ähnelt.
        /// </summary>
        public static string billingPeriodInMonthsDesc {
            get {
                return ResourceManager.GetString("billingPeriodInMonthsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already an category with this name  ähnelt.
        /// </summary>
        public static string categoryAlreadyExists {
            get {
                return ResourceManager.GetString("categoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die City ähnelt.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified city is invalid ähnelt.
        /// </summary>
        public static string CityInvalid {
            get {
                return ResourceManager.GetString("CityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color coding ähnelt.
        /// </summary>
        public static string ColorCoding {
            get {
                return ResourceManager.GetString("ColorCoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email confirmation link sent to: ähnelt.
        /// </summary>
        public static string ConfirmationLinkSentTo {
            get {
                return ResourceManager.GetString("ConfirmationLinkSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm password ähnelt.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content ähnelt.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Count ähnelt.
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Country ähnelt.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new group ähnelt.
        /// </summary>
        public static string CreateNewGroup {
            get {
                return ResourceManager.GetString("CreateNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current and upcoming surveys ähnelt.
        /// </summary>
        public static string CurrentAndUpcomingSurveys {
            get {
                return ResourceManager.GetString("CurrentAndUpcomingSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current surveys ähnelt.
        /// </summary>
        public static string CurrentSurveys {
            get {
                return ResourceManager.GetString("CurrentSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert the customer code you got in your validation mail ähnelt.
        /// </summary>
        public static string custCodeTooltip {
            get {
                return ResourceManager.GetString("custCodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer code ähnelt.
        /// </summary>
        public static string customerCode {
            get {
                return ResourceManager.GetString("customerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer name ähnelt.
        /// </summary>
        public static string customerName {
            get {
                return ResourceManager.GetString("customerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data storage period in months ähnelt.
        /// </summary>
        public static string dataRetentionPeriodInMonths {
            get {
                return ResourceManager.GetString("dataRetentionPeriodInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The time, how long you survey data is stored until it gets deleted ähnelt.
        /// </summary>
        public static string dataRetentionPeriodInMonthsDesc {
            get {
                return ResourceManager.GetString("dataRetentionPeriodInMonthsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have not created any groups yet, create your first one in group administration ähnelt.
        /// </summary>
        public static string defineGroupsModalInfo {
            get {
                return ResourceManager.GetString("defineGroupsModalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Define your first group ähnelt.
        /// </summary>
        public static string DefineYourFirstGroup {
            get {
                return ResourceManager.GetString("DefineYourFirstGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete group ähnelt.
        /// </summary>
        public static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diagram ähnelt.
        /// </summary>
        public static string diagram {
            get {
                return ResourceManager.GetString("diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left diagram type ähnelt.
        /// </summary>
        public static string DiagramTypeLeft {
            get {
                return ResourceManager.GetString("DiagramTypeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right diagram type ähnelt.
        /// </summary>
        public static string DiagramTypeRight {
            get {
                return ResourceManager.GetString("DiagramTypeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dichotomous ähnelt.
        /// </summary>
        public static string Dichotomous {
            get {
                return ResourceManager.GetString("Dichotomous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t know ähnelt.
        /// </summary>
        public static string DontKnow {
            get {
                return ResourceManager.GetString("DontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Doughnut ähnelt.
        /// </summary>
        public static string doughnut {
            get {
                return ResourceManager.GetString("doughnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can download the app here ähnelt.
        /// </summary>
        public static string downloadAppHere {
            get {
                return ResourceManager.GetString("downloadAppHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die download template ähnelt.
        /// </summary>
        public static string downloadTemplate {
            get {
                return ResourceManager.GetString("downloadTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified email address is not valid ähnelt.
        /// </summary>
        public static string EmailAddressInvalid {
            get {
                return ResourceManager.GetString("EmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The email already exists ähnelt.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email address confirmed ähnelt.
        /// </summary>
        public static string emailConfirmed {
            get {
                return ResourceManager.GetString("emailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sending email failed\nPlease try again later ähnelt.
        /// </summary>
        public static string EmailSendingFailed {
            get {
                return ResourceManager.GetString("EmailSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email sent ähnelt.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to export empty results ähnelt.
        /// </summary>
        public static string EmptyResultsExport {
            get {
                return ResourceManager.GetString("EmptyResultsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End date ähnelt.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Evaluate ähnelt.
        /// </summary>
        public static string evaluate {
            get {
                return ResourceManager.GetString("evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export results ähnelt.
        /// </summary>
        public static string ExportResults {
            get {
                return ResourceManager.GetString("ExportResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot passwort ähnelt.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free text ähnelt.
        /// </summary>
        public static string FreeText {
            get {
                return ResourceManager.GetString("FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die from ähnelt.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appropriate group size for meaningful results ähnelt.
        /// </summary>
        public static string goodAskGroupCount {
            get {
                return ResourceManager.GetString("goodAskGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to registration ähnelt.
        /// </summary>
        public static string goToRegistration {
            get {
                return ResourceManager.GetString("goToRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Green ähnelt.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group administration ähnelt.
        /// </summary>
        public static string groupAdministrationHeader {
            get {
                return ResourceManager.GetString("groupAdministrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is already a group with this name ähnelt.
        /// </summary>
        public static string groupAlreadyExists {
            get {
                return ResourceManager.GetString("groupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group code ähnelt.
        /// </summary>
        public static string groupCode {
            get {
                return ResourceManager.GetString("groupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group name ähnelt.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Groups ähnelt.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group selection ähnelt.
        /// </summary>
        public static string GroupSelection {
            get {
                return ResourceManager.GetString("GroupSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collapse navigation ähnelt.
        /// </summary>
        public static string HideNavBar {
            get {
                return ResourceManager.GetString("HideNavBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die import address file ähnelt.
        /// </summary>
        public static string importAddressFile {
            get {
                return ResourceManager.GetString("importAddressFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First download and fill the template file. Then upload it. ähnelt.
        /// </summary>
        public static string importAddressFileInfo {
            get {
                return ResourceManager.GetString("importAddressFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid customer code ähnelt.
        /// </summary>
        public static string InvalidCustCode {
            get {
                return ResourceManager.GetString("InvalidCustCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid input ähnelt.
        /// </summary>
        public static string invalidInput {
            get {
                return ResourceManager.GetString("invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid link ähnelt.
        /// </summary>
        public static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entered email address in invalid ähnelt.
        /// </summary>
        public static string invalidMailAddress {
            get {
                return ResourceManager.GetString("invalidMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid password ähnelt.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invitation to SimpleQ ähnelt.
        /// </summary>
        public static string invitationToSimpleQ {
            get {
                return ResourceManager.GetString("invitationToSimpleQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invite members ähnelt.
        /// </summary>
        public static string InviteMembers {
            get {
                return ResourceManager.GetString("InviteMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die left ähnelt.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale (3 items) ähnelt.
        /// </summary>
        public static string LikertSkale3 {
            get {
                return ResourceManager.GetString("LikertSkale3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale (4 items) ähnelt.
        /// </summary>
        public static string LikertSkale4 {
            get {
                return ResourceManager.GetString("LikertSkale4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale (5 items) ähnelt.
        /// </summary>
        public static string LikertSkale5 {
            get {
                return ResourceManager.GetString("LikertSkale5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale (6 items) ähnelt.
        /// </summary>
        public static string LikertSkale6 {
            get {
                return ResourceManager.GetString("LikertSkale6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale (7 items) ähnelt.
        /// </summary>
        public static string LikertSkale7 {
            get {
                return ResourceManager.GetString("LikertSkale7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale (8 items) ähnelt.
        /// </summary>
        public static string LikertSkale8 {
            get {
                return ResourceManager.GetString("LikertSkale8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale (9 items) ähnelt.
        /// </summary>
        public static string LikertSkale9 {
            get {
                return ResourceManager.GetString("LikertSkale9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line ähnelt.
        /// </summary>
        public static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Listing (absolute, %) ähnelt.
        /// </summary>
        public static string listing {
            get {
                return ResourceManager.GetString("listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die max ähnelt.
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium ähnelt.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die members ähnelt.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sufficient group size ähnelt.
        /// </summary>
        public static string middleAskGroupCount {
            get {
                return ResourceManager.GetString("middleAskGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize navigation ähnelt.
        /// </summary>
        public static string minimizeNav {
            get {
                return ResourceManager.GetString("minimizeNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The customer name must not be empty ähnelt.
        /// </summary>
        public static string NameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("NameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New category name ähnelt.
        /// </summary>
        public static string newCategoryName {
            get {
                return ResourceManager.GetString("newCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New group ähnelt.
        /// </summary>
        public static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No template ähnelt.
        /// </summary>
        public static string noTemplate {
            get {
                return ResourceManager.GetString("noTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This function has not been implemented yet. Please wait a few weeks. ähnelt.
        /// </summary>
        public static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not yet started ähnelt.
        /// </summary>
        public static string NotYetStarted {
            get {
                return ResourceManager.GetString("NotYetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open text answer ähnelt.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original date ähnelt.
        /// </summary>
        public static string OriginalDate {
            get {
                return ResourceManager.GetString("OriginalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other question ähnelt.
        /// </summary>
        public static string OtherQuestion {
            get {
                return ResourceManager.GetString("OtherQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password changed ähnelt.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium password ähnelt.
        /// </summary>
        public static string PasswordMedium {
            get {
                return ResourceManager.GetString("PasswordMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entered passwords do not match ähnelt.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strong password ähnelt.
        /// </summary>
        public static string PasswordStrong {
            get {
                return ResourceManager.GetString("PasswordStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weak password ähnelt.
        /// </summary>
        public static string PasswordWeak {
            get {
                return ResourceManager.GetString("PasswordWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Payment method ähnelt.
        /// </summary>
        public static string paymentMethod {
            get {
                return ResourceManager.GetString("paymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question concerning payment ähnelt.
        /// </summary>
        public static string PaymentQuestion {
            get {
                return ResourceManager.GetString("PaymentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Percent ähnelt.
        /// </summary>
        public static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Period ähnelt.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to repeat a question certain times automatically ähnelt.
        /// </summary>
        public static string periodicQuestionTooltip {
            get {
                return ResourceManager.GetString("periodicQuestionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Periodic survey... ähnelt.
        /// </summary>
        public static string PeriodicSurvey {
            get {
                return ResourceManager.GetString("PeriodicSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Periodic surveys ähnelt.
        /// </summary>
        public static string PeriodicSurveys {
            get {
                return ResourceManager.GetString("PeriodicSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please confirm your email address before logging in ähnelt.
        /// </summary>
        public static string PleaseConfirmBefore {
            get {
                return ResourceManager.GetString("PleaseConfirmBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please confirm your email address ähnelt.
        /// </summary>
        public static string PleaseConfirmYourEmail {
            get {
                return ResourceManager.GetString("PleaseConfirmYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please define groups first ähnelt.
        /// </summary>
        public static string pleaseDefineGroupsFirst {
            get {
                return ResourceManager.GetString("pleaseDefineGroupsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified ZIP code is invalid ähnelt.
        /// </summary>
        public static string PlzInvalid {
            get {
                return ResourceManager.GetString("PlzInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Polar area ähnelt.
        /// </summary>
        public static string polarArea {
            get {
                return ResourceManager.GetString("polarArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many answers, many to choose (ordered) ähnelt.
        /// </summary>
        public static string PolytomousOrderedMultiple {
            get {
                return ResourceManager.GetString("PolytomousOrderedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many answers, one to choose (ordered) ähnelt.
        /// </summary>
        public static string PolytomousOrderedSingle {
            get {
                return ResourceManager.GetString("PolytomousOrderedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many answers, many to choose (unordered) ähnelt.
        /// </summary>
        public static string PolytomousUnorderedMultiple {
            get {
                return ResourceManager.GetString("PolytomousUnorderedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many answers, one to choose (unordered) ähnelt.
        /// </summary>
        public static string PolytomousUnorderedSingle {
            get {
                return ResourceManager.GetString("PolytomousUnorderedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ZIP code ähnelt.
        /// </summary>
        public static string postCode {
            get {
                return ResourceManager.GetString("postCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Predicted price ähnelt.
        /// </summary>
        public static string predictedPrice {
            get {
                return ResourceManager.GetString("predictedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preferred billing date for each month ähnelt.
        /// </summary>
        public static string preferredBillingDay {
            get {
                return ResourceManager.GetString("preferredBillingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day of month, on which the bill is delivered ähnelt.
        /// </summary>
        public static string preferredBillingDayDesc {
            get {
                return ResourceManager.GetString("preferredBillingDayDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous ähnelt.
        /// </summary>
        public static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question concerning product ähnelt.
        /// </summary>
        public static string ProductQuestion {
            get {
                return ResourceManager.GetString("ProductQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string questionHeader {
            get {
                return ResourceManager.GetString("questionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string questionTimeDateHeader {
            get {
                return ResourceManager.GetString("questionTimeDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        public static string questionTimeTimeHeader {
            get {
                return ResourceManager.GetString("questionTimeTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radar ähnelt.
        /// </summary>
        public static string radar {
            get {
                return ResourceManager.GetString("radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Red ähnelt.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registered successfully ähnelt.
        /// </summary>
        public static string RegisteredSuccessfully {
            get {
                return ResourceManager.GetString("RegisteredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset password ähnelt.
        /// </summary>
        public static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First name of responsible person ähnelt.
        /// </summary>
        public static string responsiblePersonFirstName {
            get {
                return ResourceManager.GetString("responsiblePersonFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last name of responsible person ähnelt.
        /// </summary>
        public static string responsiblePersonLastName {
            get {
                return ResourceManager.GetString("responsiblePersonLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die right ähnelt.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as template ähnelt.
        /// </summary>
        public static string SaveAsTemplate {
            get {
                return ResourceManager.GetString("SaveAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save password ähnelt.
        /// </summary>
        public static string SavePassword {
            get {
                return ResourceManager.GetString("SavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected group: ähnelt.
        /// </summary>
        public static string SelectedGroup {
            get {
                return ResourceManager.GetString("SelectedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send email ähnelt.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send reset link ähnelt.
        /// </summary>
        public static string sendResetLink {
            get {
                return ResourceManager.GetString("sendResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click here to get the results of each survey seperately ähnelt.
        /// </summary>
        public static string singleButtonTooltip {
            get {
                return ResourceManager.GetString("singleButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single evaluation ähnelt.
        /// </summary>
        public static string singleEvaluation {
            get {
                return ResourceManager.GetString("singleEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single or trend evaluation? ähnelt.
        /// </summary>
        public static string singleOrTrendEvaluation {
            get {
                return ResourceManager.GetString("singleOrTrendEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Single survey evaluation ähnelt.
        /// </summary>
        public static string singleQuestionEvaluation {
            get {
                return ResourceManager.GetString("singleQuestionEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Specific data ähnelt.
        /// </summary>
        public static string specificData {
            get {
                return ResourceManager.GetString("specificData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start date ähnelt.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send survey ähnelt.
        /// </summary>
        public static string startSurvey {
            get {
                return ResourceManager.GetString("startSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stay logged in ähnelt.
        /// </summary>
        public static string stayLoggedIn {
            get {
                return ResourceManager.GetString("stayLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street and house number ähnelt.
        /// </summary>
        public static string streetAndHousenumber {
            get {
                return ResourceManager.GetString("streetAndHousenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Street or street number invalid ähnelt.
        /// </summary>
        public static string StreetInvalid {
            get {
                return ResourceManager.GetString("StreetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strong ähnelt.
        /// </summary>
        public static string strong {
            get {
                return ResourceManager.GetString("strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject ähnelt.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sum ähnelt.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support ähnelt.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Survey ähnelt.
        /// </summary>
        public static string survey {
            get {
                return ResourceManager.GetString("survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Survey cancelled successfully ähnelt.
        /// </summary>
        public static string SurveyCancelledSuccessfully {
            get {
                return ResourceManager.GetString("SurveyCancelledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Survey category ähnelt.
        /// </summary>
        public static string surveyCategoryHeader {
            get {
                return ResourceManager.GetString("surveyCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create survey ähnelt.
        /// </summary>
        public static string surveyCreationHeader {
            get {
                return ResourceManager.GetString("surveyCreationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        /// </summary>
        public static string surveyPreviewHeader {
            get {
                return ResourceManager.GetString("surveyPreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Survey results ähnelt.
        /// </summary>
        public static string surveyResultsHeader {
            get {
                return ResourceManager.GetString("surveyResultsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose template (recent surveys) ähnelt.
        /// </summary>
        public static string surveyTemplateHeader {
            get {
                return ResourceManager.GetString("surveyTemplateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check if you intend to repeat the survey later ähnelt.
        /// </summary>
        public static string TemplateDescription {
            get {
                return ResourceManager.GetString("TemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en ähnelt.
        /// </summary>
        public static string textEditorLanguage {
            get {
                return ResourceManager.GetString("textEditorLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timespan ähnelt.
        /// </summary>
        public static string timespan {
            get {
                return ResourceManager.GetString("timespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to ähnelt.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To group-administration ähnelt.
        /// </summary>
        public static string toGroupAdministration {
            get {
                return ResourceManager.GetString("toGroupAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to login ähnelt.
        /// </summary>
        public static string ToLogin {
            get {
                return ResourceManager.GetString("ToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Traffic lights (red, yellow, green) ähnelt.
        /// </summary>
        public static string TrafficLight {
            get {
                return ResourceManager.GetString("TrafficLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click here to get a trend view of all survey results ähnelt.
        /// </summary>
        public static string trendButtonTooltip {
            get {
                return ResourceManager.GetString("trendButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trend evaluation ähnelt.
        /// </summary>
        public static string trendEvaluation {
            get {
                return ResourceManager.GetString("trendEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  type ähnelt.
        /// </summary>
        public static string typeSmall {
            get {
                return ResourceManager.GetString("typeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unit ähnelt.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die upload chosen file ähnelt.
        /// </summary>
        public static string uploadChosenFile {
            get {
                return ResourceManager.GetString("uploadChosenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weak ähnelt.
        /// </summary>
        public static string weak {
            get {
                return ResourceManager.GetString("weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weeks ähnelt.
        /// </summary>
        public static string weeks {
            get {
                return ResourceManager.GetString("weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yellow ähnelt.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes/No ähnelt.
        /// </summary>
        public static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes/No/Don&apos;t know ähnelt.
        /// </summary>
        public static string YesNoDontKnow {
            get {
                return ResourceManager.GetString("YesNoDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can log in now ähnelt.
        /// </summary>
        public static string youCanNowLogin {
            get {
                return ResourceManager.GetString("youCanNowLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your customer code: ähnelt.
        /// </summary>
        public static string YourCustCode {
            get {
                return ResourceManager.GetString("YourCustCode", resourceCulture);
            }
        }
    }
}
