//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleQ.Webinterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add answer.
        /// </summary>
        public static string addAnswer {
            get {
                return ResourceManager.GetString("addAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add mail address.
        /// </summary>
        public static string addMailAddress {
            get {
                return ResourceManager.GetString("addMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new category.
        /// </summary>
        public static string addNewCategory {
            get {
                return ResourceManager.GetString("addNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address data.
        /// </summary>
        public static string addressData {
            get {
                return ResourceManager.GetString("addressData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answers.
        /// </summary>
        public static string answers {
            get {
                return ResourceManager.GetString("answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to add answers!.
        /// </summary>
        public static string answersButtonTooltip {
            get {
                return ResourceManager.GetString("answersButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer type.
        /// </summary>
        public static string answerTypeHeader {
            get {
                return ResourceManager.GetString("answerTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asked people (count).
        /// </summary>
        public static string askedPeopleCount {
            get {
                return ResourceManager.GetString("askedPeopleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small group, to get good results create a bigger one.
        /// </summary>
        public static string badAskGroupCount {
            get {
                return ResourceManager.GetString("badAskGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bar.
        /// </summary>
        public static string bar {
            get {
                return ResourceManager.GetString("bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base data.
        /// </summary>
        public static string baseData {
            get {
                return ResourceManager.GetString("baseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to billing period in months.
        /// </summary>
        public static string billingPeriodInMonths {
            get {
                return ResourceManager.GetString("billingPeriodInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an category with this name .
        /// </summary>
        public static string categoryAlreadyExists {
            get {
                return ResourceManager.GetString("categoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm password.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count.
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert the customer code you got in your validation mail.
        /// </summary>
        public static string custCodeTooltip {
            get {
                return ResourceManager.GetString("custCodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer code.
        /// </summary>
        public static string customerCode {
            get {
                return ResourceManager.GetString("customerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer name.
        /// </summary>
        public static string customerName {
            get {
                return ResourceManager.GetString("customerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data retention period in months.
        /// </summary>
        public static string dataRetentionPeriodInMonths {
            get {
                return ResourceManager.GetString("dataRetentionPeriodInMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no groups yet, switch to group administration and create your first one!.
        /// </summary>
        public static string defineGroupsModalInfo {
            get {
                return ResourceManager.GetString("defineGroupsModalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to diagram.
        /// </summary>
        public static string diagram {
            get {
                return ResourceManager.GetString("diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dichotomous.
        /// </summary>
        public static string Dichotomous {
            get {
                return ResourceManager.GetString("Dichotomous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doughnut.
        /// </summary>
        public static string doughnut {
            get {
                return ResourceManager.GetString("doughnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download the app here.
        /// </summary>
        public static string downloadAppHere {
            get {
                return ResourceManager.GetString("downloadAppHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email-address confirmed.
        /// </summary>
        public static string emailConfirmed {
            get {
                return ResourceManager.GetString("emailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evaluate.
        /// </summary>
        public static string evaluate {
            get {
                return ResourceManager.GetString("evaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finish.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forgot passwort.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to good size for good results.
        /// </summary>
        public static string goodAskGroupCount {
            get {
                return ResourceManager.GetString("goodAskGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to registration.
        /// </summary>
        public static string goToRegistration {
            get {
                return ResourceManager.GetString("goToRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppenverwaltung.
        /// </summary>
        public static string groupAdministrationHeader {
            get {
                return ResourceManager.GetString("groupAdministrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a group with this name!.
        /// </summary>
        public static string groupAlreadyExists {
            get {
                return ResourceManager.GetString("groupAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group code.
        /// </summary>
        public static string groupCode {
            get {
                return ResourceManager.GetString("groupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid input!.
        /// </summary>
        public static string invalidInput {
            get {
                return ResourceManager.GetString("invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the email address in invalid!.
        /// </summary>
        public static string invalidMailAddress {
            get {
                return ResourceManager.GetString("invalidMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invitation to simpleQ.
        /// </summary>
        public static string invitationToSimpleQ {
            get {
                return ResourceManager.GetString("invitationToSimpleQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string left {
            get {
                return ResourceManager.GetString("left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale 3.
        /// </summary>
        public static string LikertSkale3 {
            get {
                return ResourceManager.GetString("LikertSkale3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale 4.
        /// </summary>
        public static string LikertSkale4 {
            get {
                return ResourceManager.GetString("LikertSkale4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale 5.
        /// </summary>
        public static string LikertSkale5 {
            get {
                return ResourceManager.GetString("LikertSkale5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale 6.
        /// </summary>
        public static string LikertSkale6 {
            get {
                return ResourceManager.GetString("LikertSkale6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale 7.
        /// </summary>
        public static string LikertSkale7 {
            get {
                return ResourceManager.GetString("LikertSkale7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale 8.
        /// </summary>
        public static string LikertSkale8 {
            get {
                return ResourceManager.GetString("LikertSkale8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likert-skale 9.
        /// </summary>
        public static string LikertSkale9 {
            get {
                return ResourceManager.GetString("LikertSkale9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line.
        /// </summary>
        public static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listing (absolute, %).
        /// </summary>
        public static string listing {
            get {
                return ResourceManager.GetString("listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max.
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size of the group is ok, could be better for more generic results.
        /// </summary>
        public static string middleAskGroupCount {
            get {
                return ResourceManager.GetString("middleAskGroupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new category name ....
        /// </summary>
        public static string newCategoryName {
            get {
                return ResourceManager.GetString("newCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no template.
        /// </summary>
        public static string noTemplate {
            get {
                return ResourceManager.GetString("noTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open text-answer.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment method.
        /// </summary>
        public static string paymentMethod {
            get {
                return ResourceManager.GetString("paymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to percent.
        /// </summary>
        public static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klick to repeat a question certain times automatically.
        /// </summary>
        public static string periodicQuestionTooltip {
            get {
                return ResourceManager.GetString("periodicQuestionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define groups first!.
        /// </summary>
        public static string pleaseDefineGroupsFirst {
            get {
                return ResourceManager.GetString("pleaseDefineGroupsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polar-area.
        /// </summary>
        public static string polarArea {
            get {
                return ResourceManager.GetString("polarArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many answers, many to choose (ordered).
        /// </summary>
        public static string PolytomousOrderedMultiple {
            get {
                return ResourceManager.GetString("PolytomousOrderedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many answers, one to choose (ordered).
        /// </summary>
        public static string PolytomousOrderedSingle {
            get {
                return ResourceManager.GetString("PolytomousOrderedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many answers, many to choose (unordered).
        /// </summary>
        public static string PolytomousUnorderedMultiple {
            get {
                return ResourceManager.GetString("PolytomousUnorderedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many answers, one to choose (unordered).
        /// </summary>
        public static string PolytomousUnorderedSingle {
            get {
                return ResourceManager.GetString("PolytomousUnorderedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to post code.
        /// </summary>
        public static string postCode {
            get {
                return ResourceManager.GetString("postCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predicted price.
        /// </summary>
        public static string predictedPrice {
            get {
                return ResourceManager.GetString("predictedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferred billing date for ervery month.
        /// </summary>
        public static string preferredBillingDay {
            get {
                return ResourceManager.GetString("preferredBillingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string previous {
            get {
                return ResourceManager.GetString("previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string questionHeader {
            get {
                return ResourceManager.GetString("questionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date.
        /// </summary>
        public static string questionTimeDateHeader {
            get {
                return ResourceManager.GetString("questionTimeDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string questionTimeTimeHeader {
            get {
                return ResourceManager.GetString("questionTimeTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radar.
        /// </summary>
        public static string radar {
            get {
                return ResourceManager.GetString("radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save as template.
        /// </summary>
        public static string SaveAsTemplate {
            get {
                return ResourceManager.GetString("SaveAsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send reset link.
        /// </summary>
        public static string sendResetLink {
            get {
                return ResourceManager.GetString("sendResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click here, you can look on the results of every servy each..
        /// </summary>
        public static string singleButtonTooltip {
            get {
                return ResourceManager.GetString("singleButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single-evaluation.
        /// </summary>
        public static string singleEvaluation {
            get {
                return ResourceManager.GetString("singleEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single- or trend-evaluation?.
        /// </summary>
        public static string singleOrTrendEvaluation {
            get {
                return ResourceManager.GetString("singleOrTrendEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single survey evaluation.
        /// </summary>
        public static string singleQuestionEvaluation {
            get {
                return ResourceManager.GetString("singleQuestionEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific data.
        /// </summary>
        public static string specificData {
            get {
                return ResourceManager.GetString("specificData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send out survey.
        /// </summary>
        public static string startSurvey {
            get {
                return ResourceManager.GetString("startSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stay logged in.
        /// </summary>
        public static string stayLoggedIn {
            get {
                return ResourceManager.GetString("stayLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street and house number.
        /// </summary>
        public static string streetAndHousenumber {
            get {
                return ResourceManager.GetString("streetAndHousenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strong.
        /// </summary>
        public static string strong {
            get {
                return ResourceManager.GetString("strong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        public static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.
        /// </summary>
        public static string survey {
            get {
                return ResourceManager.GetString("survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string surveyCategoryHeader {
            get {
                return ResourceManager.GetString("surveyCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Survey.
        /// </summary>
        public static string surveyCreationHeader {
            get {
                return ResourceManager.GetString("surveyCreationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string surveyPreviewHeader {
            get {
                return ResourceManager.GetString("surveyPreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Results.
        /// </summary>
        public static string surveyResultsHeader {
            get {
                return ResourceManager.GetString("surveyResultsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose template (by last surveys).
        /// </summary>
        public static string surveyTemplateHeader {
            get {
                return ResourceManager.GetString("surveyTemplateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you do the same question later, you dont have to write everything again.
        /// </summary>
        public static string TemplateDescription {
            get {
                return ResourceManager.GetString("TemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string textEditorLanguage {
            get {
                return ResourceManager.GetString("textEditorLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timespan.
        /// </summary>
        public static string timespan {
            get {
                return ResourceManager.GetString("timespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to group-administration.
        /// </summary>
        public static string toGroupAdministration {
            get {
                return ResourceManager.GetString("toGroupAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic-lights (red,yellow,green).
        /// </summary>
        public static string TrafficLight {
            get {
                return ResourceManager.GetString("TrafficLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click this button, you can see a summarized view of all surveys.
        /// </summary>
        public static string trendButtonTooltip {
            get {
                return ResourceManager.GetString("trendButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trend-evaluation.
        /// </summary>
        public static string trendEvaluation {
            get {
                return ResourceManager.GetString("trendEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string typeSmall {
            get {
                return ResourceManager.GetString("typeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weak.
        /// </summary>
        public static string weak {
            get {
                return ResourceManager.GetString("weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        public static string weeks {
            get {
                return ResourceManager.GetString("weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes-no.
        /// </summary>
        public static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes-no-dont know.
        /// </summary>
        public static string YesNoDontKnow {
            get {
                return ResourceManager.GetString("YesNoDontKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can now log in.
        /// </summary>
        public static string youCanNowLogin {
            get {
                return ResourceManager.GetString("youCanNowLogin", resourceCulture);
            }
        }
    }
}
