//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Shared
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerOption
    {
    
        public int AnsId { get; set; }
        public int SvyId { get; set; }
        public string AnsText { get; set; }
        public bool? FirstPosition { get; set; }
    }
}
