//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleQ.Webinterface.App_LocalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add ähnelt.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add answer ähnelt.
        /// </summary>
        public static string addAnswer {
            get {
                return ResourceManager.GetString("addAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add new category ähnelt.
        /// </summary>
        public static string addNewCategory {
            get {
                return ResourceManager.GetString("addNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die answer ähnelt.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die answer type ähnelt.
        /// </summary>
        public static string answerTypeHeader {
            get {
                return ResourceManager.GetString("answerTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bar ähnelt.
        /// </summary>
        public static string bar {
            get {
                return ResourceManager.GetString("bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die count ähnelt.
        /// </summary>
        public static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die diagram ähnelt.
        /// </summary>
        public static string diagram {
            get {
                return ResourceManager.GetString("diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dichotomous ähnelt.
        /// </summary>
        public static string Dichotomous {
            get {
                return ResourceManager.GetString("Dichotomous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die doughnut ähnelt.
        /// </summary>
        public static string doughnut {
            get {
                return ResourceManager.GetString("doughnut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die from ähnelt.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gruppenverwaltung ähnelt.
        /// </summary>
        public static string groupAdministrationHeader {
            get {
                return ResourceManager.GetString("groupAdministrationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die groups ähnelt.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die invalid input! ähnelt.
        /// </summary>
        public static string invalidInput {
            get {
                return ResourceManager.GetString("invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale 3 ähnelt.
        /// </summary>
        public static string LikertSkale3 {
            get {
                return ResourceManager.GetString("LikertSkale3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale 4 ähnelt.
        /// </summary>
        public static string LikertSkale4 {
            get {
                return ResourceManager.GetString("LikertSkale4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale 5 ähnelt.
        /// </summary>
        public static string LikertSkale5 {
            get {
                return ResourceManager.GetString("LikertSkale5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale 6 ähnelt.
        /// </summary>
        public static string LikertSkale6 {
            get {
                return ResourceManager.GetString("LikertSkale6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale 7 ähnelt.
        /// </summary>
        public static string LikertSkale7 {
            get {
                return ResourceManager.GetString("LikertSkale7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale 8 ähnelt.
        /// </summary>
        public static string LikertSkale8 {
            get {
                return ResourceManager.GetString("LikertSkale8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Likert-skale 9 ähnelt.
        /// </summary>
        public static string LikertSkale9 {
            get {
                return ResourceManager.GetString("LikertSkale9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die line ähnelt.
        /// </summary>
        public static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die listing (absolute, %) ähnelt.
        /// </summary>
        public static string listing {
            get {
                return ResourceManager.GetString("listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die new category name ... ähnelt.
        /// </summary>
        public static string newCategoryName {
            get {
                return ResourceManager.GetString("newCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open text-answer ähnelt.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die percent ähnelt.
        /// </summary>
        public static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die polar-area ähnelt.
        /// </summary>
        public static string polarArea {
            get {
                return ResourceManager.GetString("polarArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many answers, many to choose (ordered) ähnelt.
        /// </summary>
        public static string PolytomousOrderedMultiple {
            get {
                return ResourceManager.GetString("PolytomousOrderedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many answers, one to choose (ordered) ähnelt.
        /// </summary>
        public static string PolytomousOrderedSingle {
            get {
                return ResourceManager.GetString("PolytomousOrderedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many answers, many to choose (unordered) ähnelt.
        /// </summary>
        public static string PolytomousUnorderedMultiple {
            get {
                return ResourceManager.GetString("PolytomousUnorderedMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many answers, one to choose (unordered) ähnelt.
        /// </summary>
        public static string PolytomousUnorderedSingle {
            get {
                return ResourceManager.GetString("PolytomousUnorderedSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... ähnelt.
        /// </summary>
        public static string questionHeader {
            get {
                return ResourceManager.GetString("questionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die date ähnelt.
        /// </summary>
        public static string questionTimeDateHeader {
            get {
                return ResourceManager.GetString("questionTimeDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... ähnelt.
        /// </summary>
        public static string questionTimeTimeHeader {
            get {
                return ResourceManager.GetString("questionTimeTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die radar ähnelt.
        /// </summary>
        public static string radar {
            get {
                return ResourceManager.GetString("radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... ähnelt.
        /// </summary>
        public static string surveyCategoryHeader {
            get {
                return ResourceManager.GetString("surveyCategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Survey ähnelt.
        /// </summary>
        public static string surveyCreationHeader {
            get {
                return ResourceManager.GetString("surveyCreationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        /// </summary>
        public static string surveyPreviewHeader {
            get {
                return ResourceManager.GetString("surveyPreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Survey Results ähnelt.
        /// </summary>
        public static string surveyResultsHeader {
            get {
                return ResourceManager.GetString("surveyResultsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to ähnelt.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Traffic-lights (red,yellow,green) ähnelt.
        /// </summary>
        public static string TrafficLight {
            get {
                return ResourceManager.GetString("TrafficLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die type ähnelt.
        /// </summary>
        public static string typeSmall {
            get {
                return ResourceManager.GetString("typeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes-no ähnelt.
        /// </summary>
        public static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes-no-dont know ähnelt.
        /// </summary>
        public static string YesNoDontKnow {
            get {
                return ResourceManager.GetString("YesNoDontKnow", resourceCulture);
            }
        }
    }
}
