//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AskedPerson
    {
        public string PersEmail { get; set; }
        public string DepName { get; set; }
        public string CustName { get; set; }
        public string PersFirstName { get; set; }
        public string PersLastName { get; set; }
        public string PersPwdTmp { get; set; }
        public byte[] PersPwdHash { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
