//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillId { get; set; }
        public string CustCode { get; set; }
        public decimal BillPrice { get; set; }
        public System.DateTime BillDate { get; set; }
        public bool Sent { get; set; }
        public bool Paid { get; set; }
    
        [System.Web.Script.Serialization.ScriptIgnore(ApplyToOverrides = true)]
        [Newtonsoft.Json.JsonIgnore]
        public virtual Customer Customer { get; set; }
    }
}
