//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillId { get; set; }
        public string CustCode { get; set; }
        public decimal BillPrice { get; set; }
        public System.DateTime BillDate { get; set; }
        public bool Paid { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
