//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillId { get; set; }
        public int CustId { get; set; }
        public decimal BillAmount { get; set; }
        public System.DateTime BillDate { get; set; }
        public bool Payed { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
