//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Bills = new HashSet<Bill>();
            this.Departments = new HashSet<Department>();
            this.SurveyCategories = new HashSet<SurveyCategory>();
            this.AnswerTypes = new HashSet<AnswerType>();
        }
    
        public string CustCode { get; set; }
        public string CustName { get; set; }
        public string CustEmail { get; set; }
        public string CustPwdTmp { get; set; }
        public byte[] CustPwdHash { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public bool EmailConfirmed { get; set; }
        public string Street { get; set; }
        public string Plz { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public int DataStoragePeriod { get; set; }
        public int AccountingPeriod { get; set; }
        public System.DateTime AccountingDate { get; set; }
        public int PaymentMethodId { get; set; }
        public int MinGroupSize { get; set; }
        public decimal CostBalance { get; set; }
        public string AuthToken { get; set; }
        public Nullable<System.DateTime> LastTokenGenerated { get; set; }
        public int Rebate { get; set; }
        public bool Deactivated { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.Web.Script.Serialization.ScriptIgnore(ApplyToOverrides = true)]
        [Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Web.Script.Serialization.ScriptIgnore(ApplyToOverrides = true)]
        [Newtonsoft.Json.JsonIgnore]
        public virtual PaymentMethod PaymentMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.Web.Script.Serialization.ScriptIgnore(ApplyToOverrides = true)]
        [Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<Department> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.Web.Script.Serialization.ScriptIgnore(ApplyToOverrides = true)]
        [Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<SurveyCategory> SurveyCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [System.Web.Script.Serialization.ScriptIgnore(ApplyToOverrides = true)]
        [Newtonsoft.Json.JsonIgnore]
        public virtual ICollection<AnswerType> AnswerTypes { get; set; }
    }
}
