//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimpleQDBEntities : DbContext
    {
        public SimpleQDBEntities()
            : base("name=SimpleQDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AskedPerson> AskedPersons { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Contain> Contains { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DsgvoConstraint> DsgvoConstraints { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<Survey> Surveys { get; set; }
        public virtual DbSet<SurveyType> SurveyTypes { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<vw_InvalidGroupSizes> vw_InvalidGroupSizes { get; set; }
    }
}
