//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleQ.Webinterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteId { get; set; }
        public int SvyId { get; set; }
        public string CustCode { get; set; }
        public int AnsId { get; set; }
        public string VoteText { get; set; }
        public Nullable<int> SpecId { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual SpecifiedTextAnswer SpecifiedTextAnswer { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
