
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;
using NLog;
using PdfSharp.Pdf;
using SimpleQ.Webinterface.Models;
using SimpleQ.Webinterface.Properties;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;

namespace SimpleQ.Webinterface.Extensions
{
    public static class Pdf
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public static bool CreateBill(ref MemoryStream stream, Customer cust, Bill bill, Survey[] surveys, string imgPath, DateTime lastBillDate)
        {
            try
            {
                logger.Debug($"Starting bill creation (BillId: {bill.BillId}, CustCode: {bill.CustCode})");
                var doc = new Document();
                doc.Info.Title = BackendResources.SimpleQBill;
                doc.Info.Subject = BackendResources.AutoGeneratedBillDoc;
                doc.Info.Author = "SimpleQ";

                var section = doc.AddSection();
                section.PageSetup = doc.DefaultPageSetup.Clone();

                var image = section.AddParagraph();
                image.Format.Alignment = ParagraphAlignment.Right;
                var img = image.AddImage(imgPath);
                img.ScaleWidth = 0.1;
                img.ScaleHeight = 0.1;

                var title = section.AddParagraph();
                title.Format.Font.Size = 20;
                title.Format.Font.Color = new Color(0, 108, 202);
                title.Format.Alignment = ParagraphAlignment.Center;
                title.AddText(BackendResources.Bill);
                title.AddLineBreak();

                var custData = section.AddParagraph();
                custData.AddFormattedText(BackendResources.Beneficiary, TextFormat.Bold);
                custData.AddLineBreak();
                custData.AddText(cust.CustName);
                custData.AddLineBreak();
                custData.AddText(cust.Street);
                custData.AddLineBreak();
                custData.AddText($"{cust.Plz} {cust.City}");
                custData.AddLineBreak();
                custData.AddText(cust.Country);
                custData.AddLineBreak();
                custData.AddText(cust.CustEmail);
                custData.AddLineBreak();
                custData.AddLineBreak();

                var infos = section.AddParagraph();
                infos.AddFormattedText(BackendResources.CustomerCode, TextFormat.Bold);
                infos.AddText($": {bill.CustCode}");
                infos.AddLineBreak();

                infos.AddFormattedText(BackendResources.BillNumber, TextFormat.Bold);
                infos.AddText($": {bill.BillId}");

                var datePar = section.AddParagraph();
                datePar.Format.Alignment = ParagraphAlignment.Right;
                datePar.AddText(bill.BillDate.ToString(BackendResources.DateFormat));
                datePar.AddLineBreak();
                datePar.AddLineBreak();

                var table = section.AddTable();
                table.Format.Font.Size = 8;
                var width = section.PageSetup.PageWidth - section.PageSetup.LeftMargin - section.PageSetup.RightMargin;

                table.AddColumn().Width = width * 0.4f; // Survey
                table.AddColumn().Width = width * 0.3f; // Period
                table.AddColumn().Width = width * 0.1f; // Number of answers
                table.AddColumn().Width = width * 0.1f; // Price per click
                table.AddColumn().Width = width * 0.1f; // Survey price

                var header = table.AddRow();
                header.HeadingFormat = true;
                header.VerticalAlignment = VerticalAlignment.Center;
                header[0].AddParagraph().AddFormattedText(BackendResources.Survey, TextFormat.Bold);
                header[1].AddParagraph().AddFormattedText(BackendResources.Period, TextFormat.Bold);
                header[2].AddParagraph().AddFormattedText(BackendResources.NumOfAnswers, TextFormat.Bold);
                header[3].AddParagraph().AddFormattedText(BackendResources.PricePerClick, TextFormat.Bold);
                header[4].AddParagraph().AddFormattedText(BackendResources.SurveyPrice, TextFormat.Bold);

                table.SetEdge(0, header.Index, 5, 1, Edge.Bottom, BorderStyle.Single, 0.75);

                var sum = 0m;
                var i = 0;
                foreach (var svy in surveys)
                {
                    var row = table.AddRow();
                    row.Shading.Color = i % 2 == 0 ? new Color(135, 200, 255) : new Color(172, 217, 255);
                    row.TopPadding = 2;
                    row.BottomPadding = 2;
                    row.VerticalAlignment = VerticalAlignment.Center;
                    row[0].AddParagraph(svy.SvyText);

                    var startDate = svy.StartDate <= lastBillDate ? lastBillDate : svy.StartDate;
                    if (svy.EndDate <= bill.BillDate)
                        row[1].AddParagraph($"{startDate.ToString(BackendResources.DateFormat)} {BackendResources.To} {svy.EndDate.ToString(BackendResources.DateFormat)}");
                    else
                        row[1].AddParagraph($"{startDate.ToString(BackendResources.DateFormat)} {BackendResources.To} {bill.BillDate.ToString(BackendResources.DateFormat)}");

                    var amount = svy.AnswerOptions.SelectMany(a => a.Votes).Distinct().Where(v => v.VoteDate > lastBillDate).Count();
                    row[2].AddParagraph($"{amount}");
                    row[3].AddParagraph($"€ {Math.Round(svy.PricePerClick.Value, 3)}");
                    row[4].AddParagraph($"€ {Math.Round((svy.PricePerClick * amount).Value, 3)}");

                    sum += (svy.PricePerClick * amount).Value;
                    i++;
                }

                if (Math.Round(sum, 2) != Math.Round(bill.BillPrice, 2))
                {
                    //Debug.WriteLine($"!!!:{sum} != {bill.BillPrice}");
                    logger.Warn($"Possible error calculating bill price. Sum: {sum} != BillPrice: {bill.BillPrice} (BillId: {bill.BillId}, CustCode: {bill.CustCode})");
                }

                var total = table.AddRow();
                table.SetEdge(0, total.Index, 5, 1, Edge.Top, BorderStyle.Single, 0.75);
                total.TopPadding = 2;
                total.BottomPadding = 2;
                total.VerticalAlignment = VerticalAlignment.Center;

                total[0].MergeRight = 2;
                total[0].AddParagraph().AddFormattedText(BackendResources.TotalCost, TextFormat.Bold);
                total[3].MergeRight = 1;

                var par = total[3].AddParagraph();
                par.Format.Alignment = ParagraphAlignment.Center;
                par.AddFormattedText($"€ {Math.Round(bill.BillPrice, 2)}", TextFormat.Bold);

                var servicePeriod = section.AddParagraph();
                servicePeriod.AddLineBreak();
                servicePeriod.AddFormattedText($"{BackendResources.ServicePeriod}: ", TextFormat.Bold);
                var minDate = surveys.Min(s => s.StartDate).ToString(BackendResources.DateFormat);
                servicePeriod.AddText($"{minDate} {BackendResources.To} {bill.BillDate.ToString(BackendResources.DateFormat)}");

                var greeting = section.AddParagraph();
                greeting.AddLineBreak();
                greeting.AddLineBreak();
                greeting.AddText(BackendResources.BestRegards);
                greeting.AddLineBreak();
                greeting.AddText(BackendResources.YourSimpleQTeam);

                section.PageSetup.DifferentFirstPageHeaderFooter = true;
                var footer = section.Footers.FirstPage.AddParagraph();
                footer.Format.Alignment = ParagraphAlignment.Center;
                footer.AddText(BackendResources.LegalHint);

                var renderer = new PdfDocumentRenderer(false, PdfFontEmbedding.Always)
                {
                    Document = doc
                };
                renderer.RenderDocument();
                renderer.PdfDocument.Save(stream, false);
                renderer.PdfDocument.Close();

                logger.Debug("Bill created successfullly");
                return true;
            }
            catch (Exception ex)
            {
                logger.Error(ex, "CreateBill: Creating bill failed");
                return false;
            }
        }
    }
}